alias: null
batch_size: 32
context_size: 10
decoder_hidden_size: 128
decoder_layers: 2
drop_last_loader: false
early_stop_patience_steps: -1
encoder_activation: tanh
encoder_bias: true
encoder_dropout: 0.0
encoder_hidden_size: 128
encoder_n_layers: 3
futr_exog_list: null
h: 30
hist_exog_list: null
inference_input_size: 24
input_size: -1
learning_rate: 0.001
loss: !!python/object:neuralforecast.losses.pytorch.MQLoss
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - - - quantiles
      - !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDQAAADE3NDAzNjE4MTM1NTJxAlgDAAAAY3B1cQNLA050cQRRLoACXXEAWA0AAAAxNzQw
              MzYxODEzNTUycQFhLgMAAAAAAAAAAAAAP83MTD0zM3M/
          - 0
          - !!python/tuple
            - 3
          - !!python/tuple
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - false
        - !!python/object/apply:collections.OrderedDict
          - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: null
  is_distribution_output: false
  output_names:
  - -median
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGwAAABvAAAALQAAADkAAAAwAAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGgAAABpAAAALQAAADkAAAAwAAAA
  outputsize_multiplier: 3
  training: true
max_steps: 300
num_lr_decays: -1
num_workers_loader: 0
optimizer: null
optimizer_kwargs: null
random_seed: 1
scaler_type: robust
stat_exog_list: null
val_check_steps: 100
valid_batch_size: null
valid_loss: null
